<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>0c43ebec-85de-438d-86c8-3c0be3eb3a98</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new decisionData where
		the assignedTeam is Exception , 
		the comment is "No specific team can be identified, please evaluate and reassign." ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
