<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>severity 1 rule</name>
  <uuid>75b18d02-27b5-47a0-99a9-ab7e7944af5d</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the severity of Input is 1 
then
	set decision to a new decisionData where
		the assignedTeam is Exception , 
		the comment is "The ticket is severity 1, please handle according to SOP." ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
