<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>default-value-setting</name>
  <uuid>2b58ae6f-2a17-4c1e-b807-4c2a07058e2f</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set Input to a new Ticket where
		the caller is "coworker" , 
		the class is "IT" , 
		the description is "Problem" , 
		the environment is "Windows" , 
		the riskId is "R123" , 
		the severity is sev 4 , 
		the state is opened , 
		the ticketNumber is "ICN12345" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
