<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>3047d5bf-b3ce-43c7-bf0e-a11fcf25b6e3</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new Assignment where
		the comment is "The default team has been assigned, please check the data" , 
		the teamAssignment is "Team X" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
