<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>b309bd61-6e1e-4763-b612-18eea77b1841</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new Assignment where
		the comment is "Default team assigned, please review data" , 
		the teamAssignment is "Team X" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
